### PR TITLE
Added Azure cost and pricing functions

### PR DESCRIPTION
**Pull request by yueguoguo**
* Minor updates on config initialization.  
* Added cost and pricing functions and their unit tests.

### CODE REVIEW

**Comment by andrie** [comment]
Thank you.  This is a great contribution.

Please can you modify your code as follows:

* Do not use `dplyr` or `magrittr`. This introduces a very large set of dependencies, for work that can easily be done using base R.
* Please use lowerCamelCase for object names. In a few places you use UPPERCASE names.
* Please wrap long lines manually at around 80 characters.

For roxygen documentation:

* Do not use the `@title` tag. Simply write the title of the function.  This should be a single sentence.  Any other words should go on a new line.
* Use `@inheritParams` where possible

**Comment by Alanwe** [comment]
Great addition, I had played with the billing APIs and I did think of some functions in this area. I can imagine some pretty cool plots could be added. The one challenge I became aware of is that it currently only supports PAYG(Not EA) so the rate card should be used with caution.

**Comment by yueguoguo** [comment]
@Alanwe Very good point. Thinking of putting notes somewhere. I am using Microsoft internal subscription, and currently have no way to test other offer options. Need advice. Cheers.

**Comment by andrie** [comment]
Thank you!

**Pull request merged**
