### PR TITLE
Add location as a parameter for azureCreateStorageAccount function

### PR DESCRIPTION
**Pull request by akzaidi**

### CODE REVIEW

**Comment by andrie** [comment]
Hi, Ali

Thanks for this pull request.  Can you please resubmit this against the `dev` branch?

The dev branch contains many changes to the storage API which will go into `master` imminently.

Andrie

**Comment by akzaidi** [comment]
Ah okay. Good to know. I'll come back and take a look later today. The only update was to add a location parameter option in the `createStorageAccount` function. If that's already being handled by the new API we can drop this PR.

**Comment by akzaidi** [comment]
I'll reissue. Looks like the merge from dev created some conflicts.

**Comment by akzaidi** [comment]
New PR in #53 to `dev` branch. Closing this one

**Pull request closed without merging**
